sonar.projectKey=NatanRigailo_vanishd
sonar.organization=natanrigailo
sonar.sources=app
sonar.tests=tests,tests/js
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.javascript.lcov.reportPaths=coverage-js/lcov.info
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/node_modules/**
