sonar.projectKey=NatanRigailo_vanishd
sonar.organization=natanrigailo
sonar.sources=app
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/__pycache__/**,**/*.pyc
